on:
  repository_dispatch:
    types: [on-demand-payload]

permissions:
   id-token: write
   contents: read

jobs:
  run_if_payload:
    if: ${{ github.event }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          export
      - env:
          MESSAGE: ${{ github.event.client_payload.summary }}
        run: echo $MESSAGE
      - env:
          MESSAGE: ${{ github.event.client_payload.description }}
        run: echo $MESSAGE
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: '${{ secrets.AZAPPID }}'
          tenant-id: '${{ secrets.AZTENTID }}'
          subscription-id: '${{ secrets.AZSUBID }}'
      - name: 'Run az commands'
        run: |
          az account show
          az group list

  run_if_failure:
    if: ${{ !github.event }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          export
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
