on:
  repository_dispatch:
    types: [on-demand-payload]

permissions:
   id-token: write
   contents: read

jobs:
  run_if_payload:
    if: ${{ github.event }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          export
      - env:
          MESSAGE: ${{ github.event.client_payload.summary }}
        run: echo $MESSAGE
      - env:
          MESSAGE: ${{ github.event.client_payload.description }}
        run: echo $MESSAGE
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: '${{ secrets.AZAPPID }}'
          tenant-id: '${{ secrets.AZTENTID }}'
          subscription-id: '${{ secrets.AZSUBID }}'
      - name: 'Run az commands'
        run: |
          az account show
          az group list
      - name: 'Check AKV'
        run: |
          az keyvault secret show --vault-name wldemokv --name sessmtppass -o json | jq -r .value > sessmtppass
          az keyvault secret show --vault-name wldemokv --name sessmtpuser -o json | jq -r .value > sessmtpuser
          
          sudo apt-get update
          sudo apt-get install -y s-nail || true

          cat >rawDescription <<EOOOOL
          ${{ github.event.client_payload.description }}
          EOOOOL

          cat >rawSummary <<EOOOOT
          ${{ github.event.client_payload.summary }}
          EOOOOT
          
          set -x
          cat rawSummary |sed ':a;N;$!ba;s/\n/ /g' | sed 's/"/\\"/g' > emailSummary
          
          data="$( jq -nc --arg title "${{ github.event.client_payload.summary }}" --arg body "${{ github.event.client_payload.description }} :: Requested by ${{ github.event.client_payload.userid }}" '$ARGS.named')"
          cat >emailJson2.json <<EOTT
          $data
          EOTT

          curl -X POST -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GH90DTOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/idjohnson/jekyll-blog/issues -d @emailJson2.json > gh.o.json

          export USERTLD=`echo "${{ github.event.client_payload.userid }}" | sed 's/^.*@//'`

          export GHURL=`cat gh.o.json | jq -r .url`

          # Now Send Email
          if [[ "$USERTLD" == "dontemailme.com" ]]; then
            # do not CC user
            echo "<h1>New Feature Requested</h1><p>user ${{ github.event.client_payload.userid }} has requested "`cat emailSummary`"</p><p>$GHURL</p><br/><br/>Kind Regards,<br/>Isaac Johnson" | s-nail -s "Blog: Feature $WIID Requested" -M "text/html" -S smtp=email-smtp.us-east-1.amazonaws.com:587 -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp-auth-user=`cat sessmtpuser` -S smtp-auth-password=`cat sessmtppass` -c isaac.johnson@gmail.com -r isaac@freshbrewed.science isaac.johnson@gmail.com
          else
            # may not work
            echo "<h1>New Feature Requested</h1><p>user ${{ github.event.client_payload.userid }} has requested "`cat emailSummary`"</p><p>$GHURL</p><br/><br/>Kind Regards,<br/>Isaac Johnson" | s-nail -s "Blog: Feature $WIID Requested" -M "text/html" -S smtp=email-smtp.us-east-1.amazonaws.com:587 -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp-auth-user=`cat sessmtpuser` -S smtp-auth-password=`cat sessmtppass` -c ${{ github.event.client_payload.userid }} -r isaac@freshbrewed.science isaac.johnson@gmail.com
          fi
          
          az keyvault secret show --vault-name wldemokv --name slackbuildswh -o json | jq -r .value > slackbuildswh

          

  run_if_failure:
    runs-on: ubuntu-latest
    needs: run_if_payload
    if: always() && (needs.run_if_payload.result == 'failure')
    steps:
      - run: |
          az keyvault secret show --vault-name wldemokv --name sessmtppass -o json | jq -r .value > sessmtppass
          az keyvault secret show --vault-name wldemokv --name sessmtpuser -o json | jq -r .value > sessmtpuser
          
          sudo apt-get update
          sudo apt-get install -y s-nail || true
          
          export USERTLD=`echo "${{ github.event.client_payload.userid }}" | sed 's/^.*@//'`
          echo "<h1>New Feature Requested</h1><p>user ${{ github.event.client_payload.userid }} but the formatting must have failed.  Please check the pipeline!" | s-nail -s "Blog: Feature Requested (FAIL processing)" -M "text/html" -S smtp=email-smtp.us-east-1.amazonaws.com:587 -S smtp-use-starttls -S ssl-verify=ignore -S smtp-auth=login -S smtp-auth-user=`cat sessmtpuser` -S smtp-auth-password=`cat sessmtppass` -c isaac.johnson@gmail.com -r isaac@freshbrewed.science isaac.johnson@gmail.com
      - env:
          MESSAGE: ${{ github.event.client_payload.message }}
        run: echo $MESSAGE
